services:
  mysql:
    image: mysql:8.0
    container_name: task_manager_api_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task_manager_api_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: task_manager_api_phpmyadmin
    restart: unless-stopped
    environment: 
      PMA_HOST: mysql
      PMA_USER: task_manager_api_user
      PMA_PASSWORD: task_manager_api_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - task_manager_api_network

volumes:
  mysql_data:

networks:
  task_manager_api_network:
